name: 📢 Invitation to the YouthIcon Organization 
  
 description: I would like to be a part of the YouthIcon community. 
  
 title: "Please invite me to the GitHub Community Organization" 
  
 labels: [invite me to the organisation] 
  
 body: 
   - type: input 
     id: name 
     attributes: 
       label: Name 
       placeholder: Insert your Full name here 
     validations: 
       required: true 
  
   - type: checkboxes 
     id: no-duplicate-issues 
     attributes: 
       label: "Checklist ✅" 
       options: 
         - label: "I have followed the [organisation on GitHub](https://github.com/Youth-Icon)." 
           required: true 
  
         - label: "I have joined [YouthIcon on Discord](https://discord.gg/vUHMxPvege)" 
           required: true 
  
         - label: "NOTE: Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. Do this by finding your name in the [GitHub organisation list](https://github.com/orgs/Youth-Icon/people) and change the dropdown to public." 
           required: true